version: '3.6'
services:
    repo:
        image: verdaccio/verdaccio
        restart: always
        ports:
            - 4873:4873
        volumes:
        - ./verdaccio-config.yaml:/verdaccio/conf/config.yaml
    repacker:
        image: smuel770/vscode-extentions-repacker:11
        deploy:
            replicas: 0
        tty: true
        environment:
            HTTP_PROXY: 
            HTTPS_PROXY: 
            NO_PROXY: repo,127.0.0.1,localhost
        volumes:
            - ./repacker-config.json:/root/.vsix-to-npm/config.json
            - $HOME/.npmrc:/root/.npmrc
    repacker-debug:
        image: smuel770/vscode-extentions-repacker:11
        depends_on:
            - repo
        deploy:
            replicas: 0
        entrypoint: ["/bin/sh", -c]
        command: ["cat"]
        # restart: 
        tty: true
        environment:
            HTTP_PROXY: 
            HTTPS_PROXY: 
            NO_PROXY: repo,127.0.0.1,localhost
        volumes:
            - ./repacker-config.json:/root/.vsix-to-npm/config.json
